WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "main.py", line 314, in <module>
Traceback (most recent call last):
  File "main.py", line 314, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "main.py", line 314, in <module>
  File "main.py", line 314, in <module>
    args.local_rank = setup_ddp()
  File "main.py", line 289, in setup_ddp
    args.local_rank = setup_ddp()
  File "main.py", line 289, in setup_ddp
    dist.init_process_group(backend='nccl')
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
    dist.init_process_group(backend='nccl')
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
        args.local_rank = setup_ddp()args.local_rank = setup_ddp()

  File "main.py", line 289, in setup_ddp
  File "main.py", line 289, in setup_ddp
    dist.init_process_group(backend='nccl')
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
    dist.init_process_group(backend='nccl')
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 897, in _new_process_group_helper
    default_pg = _new_process_group_helper(    
    default_pg = _new_process_group_helper(
default_pg = _new_process_group_helper(
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 897, in _new_process_group_helper
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 897, in _new_process_group_helper
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 897, in _new_process_group_helper
    pg = ProcessGroupNCCL(prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
        pg = ProcessGroupNCCL(prefix_store, group_rank, group_size, pg_options)pg = ProcessGroupNCCL(prefix_store, group_rank, group_size, pg_options)

    RuntimeErrorRuntimeErrorpg = ProcessGroupNCCL(prefix_store, group_rank, group_size, pg_options): 
: ProcessGroupNCCL is only supported with GPUs, no GPUs found!ProcessGroupNCCL is only supported with GPUs, no GPUs found!

RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 170913) of binary: /shared/home/xvoice/anaconda3/envs/signL/bin/python
Traceback (most recent call last):
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-07-16_18:45:02
  host      : login-n1-eno2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 170914)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-07-16_18:45:02
  host      : login-n1-eno2
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 170915)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-07-16_18:45:02
  host      : login-n1-eno2
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 170916)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-16_18:45:02
  host      : login-n1-eno2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 170913)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
